### ISSUE TITLE
루비콘 멤버 인증 기능 구현

### ISSUE THREAD

**Issue by evan-moon** [Lubycon/lubycon-home#27]
루비콘 인터널 툴 개발 수요에 따라 인증 기능이 필요할 것 같음

## 토큰
JWT 사용?

## 권한
사용자의 권한이 나누어짐 (Lubycon멤버 / Lubycon 스터디와 같이 특정 권한만 허가된 외부 인원 / 멤버 아닌 사람)

## 예상 인터널 기능
루비콘 멤버 관리 (멤버 추가 / 삭제)
루비콘 스터디 주제 조회 기능
일정관리 (Google Calendar 연동)
프로젝트 신청 기능 (Chit Chat이나 멘토링 프로젝트 같은 거)

**Comment by danielzepp** [comment]
그냥 DB에 유저 생성-삭제 하는것도 좋지만, https://firebase.google.com/docs/auth
이거 써보는거도 좋을거같습니다. 어차피 google 계정은 있을테니까.. 
이걸로 계정 연동하고 구글 캘린더 권한같은거 받아올 수 있지않을까염? (조사 안해봄)

**Comment by evan-moon** [comment]
요걸로 하면 간단하긴 한데, 권한이 분리된 유저 그룹까지 관리하기는 쉽지 않을 것 같네요 ㅜㅜ

**Comment by evan-moon** [comment]
https://firebase.google.com/docs/auth/admin/manage-users?hl=ko 요 기능을 사용하면 파베에서 제공해주는 퍼미션들을 사용하여 구현가능 할 것도 같습니다.

요걸로 테스트 해볼게요

**Comment by evan-moon** [comment]
인증 자체는 Firebase로 함. 근데 파베에서 지원해주는 유저 프로퍼티가 제한적이라서 Realtime Database에 uid로 FK가 걸린 별도의 스키마가 필요함
